# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180613_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='portfolio',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=30),
        ),
    ]
