# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20180922_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='portfolio',
        ),
    ]
