# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employeeprofile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='portfolio',
            field=models.URLField(null=True, unique=True),
        ),
    ]
