# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180610_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='tag',
            new_name='Skills',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='portfolio',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
