# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20180922_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='Skills',
            new_name='tag',
        ),
    ]
