# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20180922_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='portfolio',
            field=models.URLField(unique=True),
        ),
    ]
