# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180922_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='portfolio',
            field=models.URLField(null=True),
        ),
    ]
