# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20180922_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='portfolio',
        ),
    ]
