# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_companyprofile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='portfolio',
            field=models.URLField(null=True, unique=True),
        ),
    ]
