# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_companyprofile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_location',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
