# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20180924_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
