# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20180605_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Image size of 1200 x 650'),
        ),
    ]
