# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20180922_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Image size of 1697 x 650'),
        ),
    ]
