# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20180925_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Image size of 900 x 650'),
        ),
    ]
